"""ibm/granite-3.0-3b-a800m-instruct. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "ibm/granite-3.0-3b-a800m-instruct"
KIND = "chat"
CATALOG_URL = "https://build.nvidia.com/ibm/granite-3.0-3b-a800m-instruct"
API_AVAILABLE = True

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
