"""nvidia/nv-embedqa-mistral-7b-v2. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "nvidia/nv-embedqa-mistral-7b-v2"
KIND = "embeddings"
CATALOG_URL = "https://build.nvidia.com/nvidia/nv-embedqa-mistral-7b-v2"
API_AVAILABLE = True

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
