"""arc/evo2-7b-forward. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "arc/evo2-7b-forward"
KIND = "specialized"
CATALOG_URL = "https://build.nvidia.com/arc/evo2-7b-forward"
API_AVAILABLE = False

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
