"""poolside/laguna-xs-2.1. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "poolside/laguna-xs-2.1"
KIND = "chat"
CATALOG_URL = "https://build.nvidia.com/poolside/laguna-xs-2.1"
API_AVAILABLE = True

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
