"""stabilityai/stable-diffusion-3_5-large. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "stabilityai/stable-diffusion-3_5-large"
KIND = "specialized"
CATALOG_URL = "https://build.nvidia.com/stabilityai/stable-diffusion-3_5-large"
API_AVAILABLE = False

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
