import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { buildModelCatalog } from "../lib/model-catalog.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const api = JSON.parse(await readFile(resolve(root, "data/nvidia-models.json"), "utf8"));
const catalog = JSON.parse(await readFile(resolve(root, "data/nvidia-catalog.json"), "utf8"));
const models = buildModelCatalog(api.models, catalog.models);
const modelRoot = resolve(root, "models");

for (const model of models) {
  const [provider, name] = model.id.split("/");
  if (!/^[a-zA-Z0-9_.-]+$/.test(provider) || !/^[a-zA-Z0-9_.-]+$/.test(name)) throw new Error("Unsafe model ID in catalog.");
  const path = resolve(modelRoot, provider, `${name}.py`);
  if (!path.startsWith(modelRoot + sep)) throw new Error("Model path is outside models/.");
  await mkdir(dirname(path), { recursive: true });
  const content = `"""${model.id}. Generated by npm run models:generate."""\n\nimport sys\nfrom pathlib import Path\n\nsys.path.insert(0, str(Path(__file__).resolve().parents[1]))\nfrom _client import run\n\nMODEL_ID = ${JSON.stringify(model.id)}\nKIND = ${JSON.stringify(model.kind)}\nCATALOG_URL = ${JSON.stringify(model.url)}\nAPI_AVAILABLE = ${model.apiAvailable ? "True" : "False"}\n\nif __name__ == "__main__":\n    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)\n`;
  if (process.argv.includes("--check")) {
    let actual = "";
    try { actual = await readFile(path, "utf8"); } catch { /* Report missing generated files below. */ }
    if (actual !== content) throw new Error(`Regenerate Python examples: ${model.id}`);
  } else await writeFile(path, content);
}
console.log(`${process.argv.includes("--check") ? "Verified" : "Generated"} ${models.length} Python model entries.`);
