"""aisingapore/sea-lion-7b-instruct. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "aisingapore/sea-lion-7b-instruct"
KIND = "chat"
CATALOG_URL = "https://build.nvidia.com/aisingapore/sea-lion-7b-instruct"
API_AVAILABLE = True

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
