"""google/diffusiongemma-26b-a4b-it. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "google/diffusiongemma-26b-a4b-it"
KIND = "chat"
CATALOG_URL = "https://build.nvidia.com/google/diffusiongemma-26b-a4b-it"
API_AVAILABLE = True

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
