"""z-ai/glm-5.3-flash. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "z-ai/glm-5.3-flash"
KIND = "chat"
CATALOG_URL = "https://build.nvidia.com/z-ai/glm-5-3-flash"
API_AVAILABLE = True

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
