"""meta/llama-guard-4-12b. Generated by npm run models:generate."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _client import run

MODEL_ID = "meta/llama-guard-4-12b"
KIND = "chat"
CATALOG_URL = "https://build.nvidia.com/meta/llama-guard-4-12b"
API_AVAILABLE = True

if __name__ == "__main__":
    run(MODEL_ID, KIND, CATALOG_URL, API_AVAILABLE)
